######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 9 23:42:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SDialog.h
FORMS += sdialog.ui
SOURCES += main.cpp SDialog.cpp
